run:
  deadline: 5m

issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - misspell
    - goimports
    - ineffassign
    - gofmt
    - govet
    - unconvert
    - megacheck
    - typecheck
