name: Tests
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - "1.18"
        - "1.19"
        - "1.20"
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-go-installation: true
        skip-cache: true

    - name: Testing
      run: go test -v ./...